services:
  laptop:
    build:
      context: .
      dockerfile: docker/laptop/Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=67
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
